# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado_project/SEA-master/Examples/FPGA/4.Module-Interface/DAC-Interface/DAC_Demo/DAC_Demo.srcs/sources_1/ip/Triangle_Rom/Triangle_Rom.xci
# IP: The module: 'Triangle_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_project/SEA-master/Examples/FPGA/4.Module-Interface/DAC-Interface/DAC_Demo/DAC_Demo.srcs/sources_1/ip/Triangle_Rom/Triangle_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Triangle_Rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/vivado_project/SEA-master/Examples/FPGA/4.Module-Interface/DAC-Interface/DAC_Demo/DAC_Demo.srcs/sources_1/ip/Triangle_Rom/Triangle_Rom.xci
# IP: The module: 'Triangle_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_project/SEA-master/Examples/FPGA/4.Module-Interface/DAC-Interface/DAC_Demo/DAC_Demo.srcs/sources_1/ip/Triangle_Rom/Triangle_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Triangle_Rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
